### PR TITLE
CMake: Add option to use MPI F08 module

### LINKED ISSUE #34: "use mpi_f08" instead of "include mpif.h"
First of all thanks for the great unit test environment!

Reading  [Halo_mod](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/master/Examples/MPI_Halo/src/Halo.F90) I noticed, that "include mpif.h" is used.
(Other modules like [PF_MpiTestCase](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/master/src/pfunit/core/MpiTestCase.F90) already have "use mpi")

Using mpi with "include mpif.h" is outdated and should not be done anymore. Instead think about putting "use mpi" or even better (for all functionality) "use mpi_f08".

From the [mpi forum](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node411.html):

Instead of using mpif.h, the use of the mpi_f08 or mpi module is strongly encouraged for the following reasons:

- Most mpif.h implementations do not include compile-time argument checking.
- Therefore, many bugs in MPI applications remain undetected at compile-time, such as:
  - Missing ierror as last argument in most Fortran bindings.
  - Declaration of a status as an INTEGER variable instead of an INTEGER array with size MPI_STATUS_SIZE.
  - Incorrect argument positions; e.g., interchanging the count and datatype arguments.
  - Passing incorrect MPI handles; e.g., passing a datatype instead of a communicator.
- The migration from mpif.h to the mpi module should be relatively straightforward (i.e., substituting include 'mpif.h' after an implicit statement by use mpi before that implicit statement) as long as the application syntax is correct.
- Migrating portable and correctly written applications to the mpi module is not expected to be difficult. No compile or runtime problems should occur because an mpif.h include file was always allowed to provide explicit Fortran interfaces.

### PR DESCRIPTION
**Pull request by ZedThree**
Closes #34 

Rather than the `pf_mpi_defines.fh` header, we could instead use add all the definitions directly to the `pf-mpi-defines` target for the same effect. The differences is that with the header we keep the set of "exposed" preprocessor macros minimal.

Note that this also relies on the F2008 ability to do `type (integer)` so that we can do the slightly nicer `type (PF_MPI_COMM_TYPE)`. It is possible to have the macro be `PF_MPI_COMM_TYPE=type(MPI_Comm)/integer` and use `PF_MPI_COMM_TYPE` directly in the code instead.

### CODE REVIEW

**Comment by tclune** [comment]
I'll try to look at this more closely over the weekend.  Dealing with a vicious set of compiler workarounds for yaFyaml/gFTL layers.  (Apparently some compilers don't like the deeply recursive structure necessary to represent a general YAML node.)

All of the compilers currently supported accept `type(integer)` so I think you suggestion is just fine.

File: src/pfunit/core/MpiTestCase.F90 [hunk 1]
```diff
@@ -24,7 +25,7 @@
 !-------------------------------------------------------------------------------
 
 module PF_MpiTestCase
-   use mpi
+   use PF_MPI_MODULE
```
Comment (tclune) [inline src/pfunit/core/MpiTestCase.F90:28]: I am a little bit concerned that this approach causes problems with CMake's dependency generator.   I know in the past I've had issues with projects where the module name is defined by the preprocessor.  Maybe this case is safe though?  Or CMake has improved to use the defines that are known?

**Review by tclune — APPROVED** [review]

File: src/pfunit/core/MpiTestCase.F90 (hunk 1 above)
Comment (ZedThree) [reply src/pfunit/core/MpiTestCase.F90:28]: I'm reasonably confident that is safe -- CMake is now pretty good with preprocessing before doing the dependency tree.

If not, the below might be better:
```fortran
#ifdef PF_USE_MPI_F08
    use mpi_f08
#else
    use mpi
#endif
```

Comment (tclune) [reply src/pfunit/core/MpiTestCase.F90:28]: ok - I'll keep that in mind.  For now your changes pass the regression tests, so probably good as you said.
